### ISSUE TITLE
Command line arguments not working

### ISSUE THREAD

**Issue by SweeWarman** [nasa/cFS#86] opened 2020-05-15 12:13 UTC
**Describe the bug**
Command line arguments are not being parsed.

**To Reproduce**
1. Compile cFS
2. Run ./core-cpu1 --help

**Expected behavior**
Display help information

**Code snips**
The issue seems to be [here](https://github.com/nasa/osal/blob/c2bcebbc4d7e60a41b604e9acfc8af3c60b8536a/src/bsp/pc-linux/src/bsp_start.c#L169-L170). According to the man pages, getopts and getopt_long both require argc and argv passed on without modifications.

**System observed on:**
 - Hardware: x86
 - OS: Ubuntu LTS 18.04
 - Versions: 
     - cFE 6.7.17 (95f34d2), 
     - OSAL 5.0.16 (c2bcebb), 
     -  PSP 1.4.11 (37ee8eb)

**Reporter Info**
NASA LARC

**Comment by skliper** [comment] 2020-06-12 16:43
Duplicate of nasa/OSAL#499

**Closed** 2020-06-12 16:44 UTC
Labels: duplicate
